export enum ConvertingType {
    FREQUENCY = "FREQUENCY",
    GENRE = "GENRE",
    TEMPO = "TEMPO",
    INSTRUMENT = "INSTRUMENT",
    ENERGY = "ENERGY",
    SPEECH = "SPEECH",
    AIO = "AIO"
}

export enum SaveAndReturnOption {
    SAVE_AND_RETURN_ID = "SAVE_AND_RETURN_ID",
    SAVE_AND_RETURN_DEMO = "SAVE_AND_RETURN_DEMO",
    RETURN_DEMO = "RETURN_DEMO",

}

export enum Genre {
    ROCK = "ROCK",
    POP = "POP",
    ELECTRONIC = "ELECTRONIC",
    HIP_HOP = "HIP_HOP",
    JAZZ = "JAZZ",
    BLUES = "BLUES",
    COUNTRY = "COUNTRY",
    CLASSICAL = "CLASSICAL",
    REGGAE = "REGGAE",
    FOLK = "FOLK",
    WORLD = "WORLD",
    LATIN = "LATIN",
    RNB = "RNB",
    METAL = "METAL",
    PUNK = "PUNK",
    FUNK = "FUNK",
    SOUL = "SOUL",
    DISCO = "DISCO",
    GOSPEL = "GOSPEL",
    OTHER = "OTHER"
}


export enum Tempo {
    LARGHISSIMO = "LARGHISSIMO",
    ADAGISSIMO = "ADAGISSIMO",
    GRAVE = "GRAVE",
    LARGO = "LARGO",
    ADAGIO = "ADAGIO",
    LARGHETTO = "LARGHETTO",
    ADAGIETTO = "ADAGIETTO",
    LENTO = "LENTO",
    ANDANTE = "ANDANTE",
    ANDANTINO = "ANDANTINO",
    MARCIA_MODERATO = "MARCIA_MODERATO",
    ANDANTE_MODERATO = "ANDANTE_MODERATO",
    MODERATO = "MODERATO",
    ALLEGRETTO = "ALLEGRETTO",
    ALLEGRO_MODERATO = "ALLEGRO_MODERATO",
    ALLEGRO = "ALLEGRO",
    MOLTO_ALLEGRO = "MOLTO_ALLEGRO",
    VIVACE = "VIVACE",
    VIVACISSIMO = "VIVACISSIMO",
    ALLEGRISIMO = "ALLEGRISIMO",
    PRESTO = "PRESTO",
    PRESTISSIMO = "PRESTISSIMO",
    OTHER = "OTHER"
}

export enum Energy {
    high = 'high',
    mid = 'mid',
    low = 'low',
    other = 'other',
}

export enum Instrument {
    ACOUSTIC_BASS = "ACOUSTIC_BASS",
    ACOUSTIC_GUITAR = "ACOUSTIC_GUITAR",
    ALTO_SAXOPHONE = "ALTO_SAXOPHONE",
    BACKING_VOCALS = "BACKING_VOCALS",
    BANJO = "BANJO",
    BARITONE_SAXOPHONE = "BARITONE_SAXOPHONE",
    BASS = "BASS",
    BASS_CLARINET = "BASS_CLARINET",
    BASS_GUITAR = "BASS_GUITAR",
    BASS_SYNTH = "BASS_SYNTH",
    CELLO = "CELLO",
    CHURCH_ORGAN = "CHURCH_ORGAN",
    CLARINET = "CLARINET",
    CLASSICAL_GUITAR = "CLASSICAL_GUITAR",
    CONTRABASS = "CONTRABASS",
    COWBELL = "COWBELL",
    DRUMS = "DRUMS",
    ELECTRIC_BASS = "ELECTRIC_BASS",
    ELECTRIC_GUITAR = "ELECTRIC_GUITAR",
    ELECTRIC_PIANO = "ELECTRIC_PIANO",
    FLUTE = "FLUTE",
    FRENCH_HORN = "FRENCH_HORN",
    GRAND_PIANO = "GRAND_PIANO",
    HAMMOND_ORGAN = "HAMMOND_ORGAN",
    HARP = "HARP",
    HARPSICHORD = "HARPSICHORD",
    HORN_SECTION = "HORN_SECTION",
    KEYBOARD = "KEYBOARD",
    LEAD_GUITAR = "LEAD_GUITAR",
    LEAD_SYNTH = "LEAD_SYNTH",
    MARACAS = "MARACAS",
    MARIMBA = "MARIMBA",
    MIXING_DESK = "MIXING_DESK",
    OBOE = "OBOE",
    ORCHESTRA_HIT = "ORCHESTRA_HIT",
    ORGAN = "ORGAN",
    OTHER = "OTHER",
    OUD = "OUD",
    OVERDRIVEN_GUITAR = "OVERDRIVEN_GUITAR",
    PAD_SYNTH = "PAD_SYNTH",
    PERCUSSION = "PERCUSSION",
    PIANO = "PIANO",
    RHYTHM_GUITAR = "RHYTHM_GUITAR",
    SAXOPHONE = "SAXOPHONE",
    SHAKER = "SHAKER",
    SLIDE_GUITAR = "SLIDE_GUITAR",
    SOPRANO_SAXOPHONE = "SOPRANO_SAXOPHONE",
    STEEL_DRUMS = "STEEL_DRUMS",
    STRINGS = "STRINGS",
    SYNTH_BASS = "SYNTH_BASS",
    SYNTH_BRASS = "SYNTH_BRASS",
    SYNTH_CHOIR = "SYNTH_CHOIR",
    SYNTH_DRUMS = "SYNTH_DRUMS",
    SYNTH_GUITAR = "SYNTH_GUITAR",
    SYNTH_KEYS = "SYNTH_KEYS",
    SYNTH_LEAD = "SYNTH_LEAD",
    SYNTH_ORCHESTRA = "SYNTH_ORCHESTRA",
    SYNTH_PAD = "SYNTH_PAD",
    SYNTH_PLUCK = "SYNTH_PLUCK",
    TALKING_DRUM = "TALKING_DRUM",
    TAMBORA = "TAMBORA",
    TAMBOURINE = "TAMBOURINE",
    TENOR_SAXOPHONE = "TENOR_SAXOPHONE",
    TIMBALES = "TIMBALES",
    TIMPANI = "TIMPANI",
    TRUMPET = "TRUMPET",
    TROMBONE = "TROMBONE",
    TUBA = "TUBA",
    UKULELE = "UKULELE",
    VIOLA = "VIOLA",
    VIOLIN = "VIOLIN",
    VOCALS = "VOCALS",
    WHISTLE = "WHISTLE",
    WURLITZER_PIANO = "WURLITZER_PIANO",
    XYLOPHONE = "XYLOPHONE"
}

export enum Sentiment {
    LOVE = "LOVE",
    JOY = "JOY",
    ANGER = "ANGER",
    SADNESS = "SADNESS",
    FEAR = "FEAR",
    SURPRISE = "SURPRISE",
    TRUST = "TRUST",
    DISGUST = "DISGUST",
    NEUTRAL = "NEUTRAL",
}


export interface AioOptionsDto {
    name: string,
    type: ConvertingType,
    saveAndReturnOption: SaveAndReturnOption,
    useIntervals?: boolean,
    intervalCount?: number,
    familyCount?: number,
    gradientSplitCount?: number,
    genre?: Genre,
    instrument?: Instrument,
    tempo?: Tempo
    sentiment?: Sentiment,
    config?: string,
    user: string,
    useCustomFft?: boolean,
}

export interface Config {
    name: string,
    type: Genre | Tempo | Energy | Sentiment | Instrument,
    colors: string[];
}